---
- name: Get Response
  wait_for_connection:
    delay: 15
    timeout: 30

- name: Update Server
  apt: upgrade=dist
  tags: update

- name: Development Tools
  apt:
    name: ['gcc', 'g++', 'curl', 'git']
    state: latest
    update_cache: yes
  tags: devtools