---
- name: Get Response
  wait_for_connection:
    delay: 15
    timeout: 30

- name: Update Server
  apt: upgrade=dist
  tags: update

- name: Install Git
  apt: name=git state=present update_cache=yes
  tags: npm