- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Update Server
      yum:
        name: '*'
        state: latest
    - name: Install NGINX
      yum:
        name: nginx
        state: latest