- hosts: localhost
  connection: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Update Server
      yum:
        name: '*'
        state: installed  
    - name: Install NGINX
      yum:
        name: nginx
        state: present