- hosts: localhost
  connection: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Install NGINX
      yum:
        use_backend: yum
        name: nginx
        state: latest
      sudo: yes