- hosts: example
  gather_facts: false
  become: yes
  tasks:
    - name: Update Server
      apt:
        name: '*'
        state: latest
    - name: Install NGINX
      apt:
        name: nginx
        state: latest
    - name: Star Nginx
      service:
        name: nginx
        state: started
        enabled: yes