- hosts: example
  gather_facts: false
  become: yes
  tasks:
    - name: Wait 300 seconds, but only start checking after 60 seconds
      wait_for_connection:
        delay: 30
        timeout: 300
    - name: Upgrade all packages to the latest version
      apt:
        update_cache: yes
    - name: Install NGINX
      apt:
        pkg: nginx
        state: latest
    - name: Star Nginx
      service:
        name: nginx
        state: started
        enabled: ye